services:
  db:
    image: postgres:14-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .deploy.env
    command: postgres -c 'max_connections=200'
    ports:
      - 5433:5432
  bothub:
    image: bothub
    container_name: bothub
    restart: always
    env_file:
      - .deploy.env
    ports:
      - "3100:3000"


volumes:
  postgres_data:


